version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/action # S3에 있는 zip 파일이 EC2에 배포될 위치를 지정합니다.
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user