spring:
  profiles:
    active: local

---
logging:
  level:
    root: warn
    com.najarang.back: debug

spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
    showSql: true
    generate-ddl: true
  url:
    base: http://localhost:8080
---
spring:
  profiles: dev
  profiles.include: devSecret
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
    showSql: true
    generate-ddl: false
  url:
    base: https://najarnag.ml