spring:
  profiles:
    active: local
    include: commonSecret
  social:
    kakao:
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  jwt:
    secret: najarang@$&