name: Spring build & deploy
on: 
  push:
    branches:
      - master
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Deliver File
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "build/libs/*.jar"
          target: "~/najarang/najarang-api"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
              SOURCE_DIR=~/najarang/najarang-api/build/libs
              FILE_NAME=`find $SOURCE_DIR/*.jar -printf "%f\n"`
              
              echo "#### change directory to $SOURCE_DIR ####"
              cd $SOURCE_DIR
              
              PID=`lsof -i TCP:8080 | awk 'NR == 2 {print $2}'`
              echo "#### PID : [ $PID ] ####"
              
              if [ -z "$PID" ]; then
                  echo "#### THERE IS NO PROCESS ####"
                    
              else
                  echo "#### KILL $PID ####"
                  sudo kill $PID
                  echo "#### config server shut down success ####":  
                  
              fi
              
              echo "#### RUN $SOURCE_DIR/$FILE_NAME ####"
              nohup java -XX:MaxMetaspaceSize=512m -XX:MetaspaceSize=256m -jar $SOURCE_DIR/$FILE_NAME &
              
              echo "#### [SUCCESS] DEPLOY SPRING ####"
